config/routes.rb
EventApp::Application.routes.draw do

  resources :events, path: '/'+I18n.t("models.events").downcase do
    member {
      get :request_participation
    }

    resources :polls, path: '/'+I18n.t("models.polls").downcase do
      member {
        post :like
        post :dislike
      }
    end

    resources :items, path: '/'+I18n.t("models.items").downcase
    resources :comments, path: '/'+I18n.t("models.comments").downcase

  end

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  authenticated :user do
    root :to => "events#index"
  end
  unauthenticated :user do
    devise_scope :user do 
      get "/" => "devise/sessions#new"
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :event
  sync :all
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  include ApplicationHelper

  before_action :find_event

  before_action :set_item, only: [:show, :edit, :update, :destroy]

  before_action :valid_super_user, only: [:new, :edit, :destroy]

  enable_sync only: [:create, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = @event.items.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = @event.items.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = @event.items.new(item_params)

    respond_to do |format|
      if @item.save
        # sync_new @item
        format.html { redirect_to event_items_url, notice: t("successfully_created", :model => t("models.item")) }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        # sync_update @item
        format.html { redirect_to event_items_url, notice: t("successfully_updated", :model => t("models.item")) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy

    # sync_destroy @item

    respond_to do |format|
      format.html { redirect_to event_items_url }
      format.json { head :no_content }
    end
  end

  private

    def find_event
      @event = Event.find(params[:event_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = @event.items.find(params[:id])
    end

    def valid_super_user
      unless user_can_modify?(@event)
        flash[:notice] = t("oops_not_access")
        redirect_to event_item_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :amount, :value)
    end
end

app/views/items/_form.html.erb
<%= simple_form_for([@event, @item], html: {class: 'form-vertical' }) do |f| %>

  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name, :autofocus => true %>
    <%= f.input :description %>
    <%= f.input :amount %>
    <%= f.input :value %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('cancel', :default => t("helpers.links.cancel")), event_items_path(@event), :class => 'btn' %>
  </div>

<% end %>

app/views/items/edit.html.erb
<h1><%=t('helpers.titles.edit', :model => t("models.item"))%></h1>

<%= render 'form' %>

app/views/items/index.html.erb
<%- model_class = Item -%>

<h2><%= t("models.items") %></h2>

<table class="table table-hover table-bordered table-sevented" id="table_item">

  <thead>
    <tr>
      <th id="detail">Detalhes</th>
      <th><%= t("name")%></th>
      <th><%= t("description")%></th>
      <th><%= t("amount")%></th>
      <th><%= t("value")%></th>
      <% if user_can_modify?(@event) %>
        <th><%=t 'actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <%= sync partial: 'item_row', collection: @event.items %>
    <%= sync_new partial: 'item_row', resource: Item.new, direction: :append%>
  </tbody>
</table>

<br>

<% if user_can_modify?(@event) %>
  <div class="add-master-button">
    <%= link_to t('helpers.titles.new',:model => t("models.item")), new_event_item_path(@event), class: 'btn btn-primary' %>
  </div>
<% end%>

app/views/items/new.html.erb
<h1><%=t('helpers.titles.new', :model => t("models.item"))%></h1>

<%= render 'form' %>

app/views/items/show.html.erb
<p>
  <strong><%=t("name")%>:</strong>
  <%= @item.name %>
</p>

<p>
  <strong><%=t("description")%>:</strong>
  <%= @item.description %>
</p>

<p>
  <strong><%=t("amount")%>:</strong>
  <%= @item.amount %>
</p>

<p>
  <strong><%=t("value")%>:</strong>
  <%= @item.value %>
</p>

<%= link_to t('edit'), edit_event_item_path(@event, @item) %> |
<%= link_to t('back'), event_items_path %>