config/routes.rb
EventApp::Application.routes.draw do

  resources :events, path: '/'+I18n.t("models.events").downcase do
    member {
      get :request_participation
    }

    resources :polls, path: '/'+I18n.t("models.polls").downcase do
      member {
        post :like
        post :dislike
      }
    end

    resources :items, path: '/'+I18n.t("models.items").downcase
    resources :comments, path: '/'+I18n.t("models.comments").downcase

  end

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  authenticated :user do
    root :to => "events#index"
  end
  unauthenticated :user do
    devise_scope :user do 
      get "/" => "devise/sessions#new"
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :event, counter_cache: true

  validates_presence_of :message

  sync :all, scope: :event

  scope :ordered, -> { order("created_at ASC") }
  scope :recently_updated, -> { order("updated_at DESC")}

  def to_s
    self.message
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_event
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  #before_action :valid_super_user, only: [:new, :edit, :destroy]
  enable_sync only: [:create, :update, :destroy]

  def index
    @comments = @event.comments.all
  end

  def show
    flash[:notice] = "Not implemented yet"
    redirect_to @event #Temporario
  end

  def new
    @comment = @event.comments.new
  end

  def edit
    flash[:notice] = "Not implemented yet"
    redirect_to @event #Temporario
  end

  def create
    @comment = @event.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to @event
  end

  def update
    @comment.update(comment_params)
    redirect_to @event
  end

  def destroy
    @comment.destroy
    redirect_to @event
  end

  private

  def find_event
    @event = Event.find(params[:event_id])
  end

  def set_comment
    @comment = @event.comments.find(params[:id])
  end

  def valid_super_user
    unless current_user.super_user
      flash[:notice] = t("oops_not_access")
      redirect_to event_url
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:title, :message)
  end
end

app/views/sync/comments/refetch/_event_comment.html.erb
  <div class="media-body">
    <% if comment.user == current_user or current_user.super_user %>
        <%= link_to edit_event_comment_path(comment.event, comment) do %>
            <i class="icon-edit"></i>
        <% end %>

        <%= link_to event_comment_path(comment.event, comment),
                    method: :delete,
                    #remote: true,
                    data: { confirm: 'Are you sure?' }  do %>
            <i class="icon-trash"></i>
        <% end %>
    <% end %>

    <b><%= comment.user.name %></b>: <%= h(comment.to_s).gsub("\n", "<br/>").html_safe %>

    <div class="pull-right">
        <%= comment.created_at.strftime('%H:%M:%S %d/%m/%y') %>
    </div>

  </div>

app/views/sync/comments/refetch/_trip_comment.html.erb
  <div class="media-body">
    <% if comment.user == current_user or current_user.super_user %>
        <%= link_to edit_trip_comment_path(@trip, comment) do %>
            <i class="icon-edit"></i>
        <% end %>

        <%= link_to trip_comment_path(@trip, comment),
                    method: :delete,
                    #remote: true,
                    data: { confirm: 'Are you sure?' }  do %>
            <i class="icon-trash"></i>
        <% end %>
    <% end %>

    <b><%= comment.user.name %></b>: <%= h(comment.to_s).gsub("\n", "<br/>").html_safe %>

    <div class="pull-right">
        <%= comment.created_at.strftime('%H:%M:%S %d/%m/%y') %>
    </div>

  </div>