config/routes.rb
EventApp::Application.routes.draw do

  resources :events, path: '/'+I18n.t("models.events").downcase do
    member {
      get :request_participation
    }

    resources :polls, path: '/'+I18n.t("models.polls").downcase do
      member {
        post :like
        post :dislike
      }
    end

    resources :items, path: '/'+I18n.t("models.items").downcase
    resources :comments, path: '/'+I18n.t("models.comments").downcase

  end

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  authenticated :user do
    root :to => "events#index"
  end
  unauthenticated :user do
    devise_scope :user do 
      get "/" => "devise/sessions#new"
    end
  end

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  belongs_to :event
  acts_as_votable
  sync :all
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  include ApplicationHelper

  before_action :find_event

  before_action :set_poll, only: [:show, :edit, :update, :destroy, :like, :dislike]

  before_action :valid_super_user, only: [:new, :edit, :destroy]

  enable_sync only: [:create, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def index
    @polls = @event.polls.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = @event.polls.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = @event.polls.new(poll_params)

    respond_to do |format|
      if @poll.save
        # sync_new @poll
        format.html { redirect_to event_polls_url, notice: t("successfully_created", :model => t("models.poll")) }
        format.json { render action: 'show', status: :created, location: @poll }
      else
        format.html { render action: 'new' }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        # sync_update @poll
        format.html { redirect_to event_polls_url, notice: t("successfully_updated", :model => t("models.poll")) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy

    # sync_destroy @poll

    respond_to do |format|
      format.html { redirect_to event_polls_url }
      format.json { head :no_content }
    end
  end

  def like
    @poll.liked_by current_user
    sync_update @poll
    redirect_to :back #, notice: "Thank you for like!"
  end

  def dislike
    @poll.disliked_by current_user
    sync_update @poll
    redirect_to :back #, notice: "Thank you for dislike!"
  end

  private

    def find_event
      @event = Event.find(params[:event_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = @event.polls.find(params[:id])
    end

    def valid_super_user
      unless user_can_modify?(@event)
        flash[:notice] = t("oops_not_access")
        redirect_to event_poll_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:description, :complement)
    end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/sync/polls/_poll_row.html.erb
<tr>
    <td><%= link_to poll.description, event_poll_path(@event, poll)%></td>
    <td>

        <% if current_user.voted_up_for? poll %>
            <%= link_to image_tag("like_disable.png", :size => "25x20"), like_event_poll_path(@event, poll), method: "post", class: "disable_link"%>
        <% else %>
            <%= link_to image_tag("like.png", :size => "25x20"), like_event_poll_path(@event, poll), method: "post"%>
        <% end %>
        <span class="badge"><%= poll.likes.size %></span>

        <% if current_user.voted_down_for? poll %>
            <%= link_to image_tag("dislike_disable.png", :size => "25x20"), dislike_event_poll_path(@event, poll), method: "post", class: "disable_link" %>
        <% else %>
            <%= link_to image_tag("dislike.png", :size => "25x20"), dislike_event_poll_path(@event, poll), method: "post" %>
        <% end %>
        <span class="badge"><%= poll.dislikes.size %></span>

    </td>
    <% if user_can_modify?(@event) %>
        <td class="btn_actions">
        <%= link_to t('edit', :default => t("helpers.links.edit")), edit_event_poll_path(@event, poll), :class => 'btn btn-mini' %>
        <%= link_to t('destroy', :default => t("helpers.links.destroy")),
                    event_poll_path(@event, poll),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => t('sure'))) },
                    :class => 'btn btn-mini btn-danger' %>
        </td>
    <% end %>
</tr>